### ISSUE TITLE
Review Ticket - Week 9

### ISSUE THREAD

**Issue by ridhimainukurti** [4disease/p1-donuts-new#40]
- [x] Ridhima Video
      - pell sequence, calendar (in [video](https://www.youtube.com/watch?v=Yrg6OT01GAw&ab_channel=Ridhimainukurti)), database (live)
- [x] Sam Video
      - catalan sequence & main page (in [video](https://drive.google.com/file/d/1VBPnd40CVsamgWfbp7BFFv4OznKEJSUF/view?usp=sharing)), API (live)
- [x] Kira Video
- Tasks page - Objects and arraylist
- [x] Natasha Video 
- [x] Adi Video

**Comment by jm1021** [comment]
Kira video,   I am pleased to see using classes and arraylists to build your front end todo lists.  It looks like there is some room for growth, but it pleases me to see transfer of work to a working application.  Seem like there is some opportunity to model list of tasks and a task as distinct objects, some clarity on the Object by slide or visual could have save a lot of time.  Reflections and Futures were discussed, this is good opportunity to highlight as-is and to-be more clearly.   5.5/6

**Comment by mistylavender** [comment]
Ridhima's Video
You understood and explained the code for the recursions very well. I liked how you explained the connections between your PellRecurse.java file and the parent class to give a complete overview of what is happening in the code.
It was nice how you connect the use of recursions for your sequence to a specific topic and question from college board about while loops. You did a good job explain how the two concepts relate to each other and how they differ as well.
I can see how you understand HTML and CSS well with your Calendar page and it was nice to see how you showed the actual runtime and explained the purpose of the different parts of your code in the HTML file.
Suggestions:

To even more fully show your understanding of the code, I feel that it would be helpful if you also referred a little to the controller file for your pell sequence to show how everything is connected in a more complete way. Also, for your calendar page, I think it would be nice if the calendar itself was larger and took up most of the page. Another thing that would be helpful is to make your video slightly shorter in the future.
Grading:
Topic 1 - Sequence
1/1 - collegeboard & topic connection
1/1 - command over code
1/1 - presentation professionalism
Topic 2 - Calendar
1/1 - collegeboard & topic connection
1/1 - command over code
1/1 - presentation professionalism

Total:
6/6

Kira's Video
I like how you made the tasks detailed so that the user is able to interact with them more by adding a description. I feel that this is a helpful feature.
You did a good job explaining the different parts of the task page code with the arrays and getters. You seem to have a very good understanding on the code and those concepts.
You also seem to have a good understanding of the thymeleaf that you used in your HTML and I like how you use th:each along with an array list in order to condense your code and make it more straightforward.
Suggestions:

You did a very thorough job with explaining the tasks page and its code but you forgot to also include a second topic. Also, something you can maybe add to improve the page even is more specific features and options for details about the task like setting a time.
Grading:
Topic 1 - Tasks
1/1 - collegeboard & topic connection
1/1 - command over code
1/1 - presentation professionalism
Topic 2 - I didn't see any
0/1 - collegeboard & topic connection
0/1 - command over code
0/1 - presentation professionalism

Total:
3/6

Adi's Video
You seem to have a very strong understanding of javascript with the code for your chatbot. It's nice how you add alternative phrases for the chatbot to say when it doesn't understand what the user is saying.
You have a good understanding of how while loops can be used to create an algorithm for a sequence as well.
I think you formatted the chatbot very well where it is functional and is also visually organized.
Suggestions:

You didn't make a very clear connection to a collegeboard topic when talking about your code. Also, for the chatbot, it might be helpful to set it to recognize a larger variety of phrases and words.
Grading:
Topic 1 - Chatbot
0.5/1 - collegeboard & topic connection
1/1 - command over code
1/1 - presentation professionalism
Topic 2 - Sequence
0.5/1 - collegeboard & topic connection
1/1 - command over code
1/1 - presentation professionalism

Total:
5/6
